services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: market_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d market_data"]
      interval: 5s
      timeout: 5s
      retries: 20

  ingestor:
    build:
      context: ./app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/market_data
      SYMBOL: BTCUSDT
      POLL_SECONDS: 10
      METRICS_PORT: 9100
      LOG_LEVEL: INFO
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  api:
    build:
      context: ./app
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/market_data
      LOG_LEVEL: INFO
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped


  research-ui:
    build:
      context: ./dashboard
    environment:
      API_BASE_URL: http://api:8000
      BACKTEST_LIST_LIMIT: 100
    depends_on:
      - api
    ports:
      - "8501:8501"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.54.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api
      - ingestor
      - cadvisor
    restart: unless-stopped



  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    command:
      - --docker_only=true
      - --housekeeping_interval=10s
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.2.2
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - db
    restart: unless-stopped

volumes:
  pgdata:
  grafana-data:
