from __future__ import annotations

import ast
import re
from pathlib import Path
from typing import Any

from app.backtest import build_strategy
from app.strategy_loader import REQUIRED_FUNCTIONS, StrategyDefinition, strategy_loader

STRATEGY_ID_PATTERN = re.compile(r"^[a-z][a-z0-9_]{2,63}$")
GAWAIN_STRATEGY_ROOT = Path("strategies/gawain")
_MANAGED_META_START = "# <shark_bay_managed_meta>"
_MANAGED_META_END = "# </shark_bay_managed_meta>"
_MANAGED_META_RE = re.compile(
    rf"\n?{re.escape(_MANAGED_META_START)}.*?{re.escape(_MANAGED_META_END)}\n?",
    flags=re.DOTALL,
)

MANAGED_STRATEGY_FIELDS = {
    "strategy_id",
    "name",
    "description",
    "version",
    "parameter_schema",
    "default_parameters",
}


def validate_strategy_id(strategy_id: str) -> None:
    if not STRATEGY_ID_PATTERN.fullmatch(strategy_id):
        raise ValueError("strategy_id must match ^[a-z][a-z0-9_]{2,63}$")


def validate_strategy_code(code: str) -> None:
    try:
        tree = ast.parse(code)
    except SyntaxError as exc:
        raise ValueError(f"Strategy code syntax error: {exc.msg}") from exc

    assigned_names: set[str] = set()
    functions: dict[str, ast.FunctionDef | ast.AsyncFunctionDef] = {}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            functions[node.name] = node
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    assigned_names.add(target.id)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            assigned_names.add(node.target.id)

    if "STRATEGY_META" not in assigned_names:
        raise ValueError("Strategy code must define STRATEGY_META")
    expected_signatures = {
        "required_features": ["params"],
        "prepare_features": ["df", "params"],
        "generate_signals": ["df", "params"],
    }
    for fn_name in REQUIRED_FUNCTIONS:
        if fn_name not in functions:
            args = ", ".join(expected_signatures[fn_name])
            raise ValueError(f"Strategy code must define {fn_name}({args})")
        arg_names = [arg.arg for arg in functions[fn_name].args.args]
        if arg_names != expected_signatures[fn_name]:
            args = ", ".join(expected_signatures[fn_name])
            raise ValueError(f"Strategy function {fn_name} must have signature {fn_name}({args})")


def forced_strategy_meta(payload: dict[str, Any]) -> dict[str, Any]:
    strategy_id = str(payload["strategy_id"])
    validate_strategy_id(strategy_id)
    meta = {
        "strategy_id": strategy_id,
        "name": str(payload.get("name") or strategy_id),
        "description": str(payload.get("description") or ""),
        "version": str(payload.get("version") or "0.1.0"),
        "strategy_type": "signal_strategy",
        "research_only": True,
        "parameter_schema": dict(payload.get("parameter_schema") or {}),
        "default_parameters": dict(payload.get("default_parameters") or {}),
    }
    return meta


def strip_managed_meta(source: str) -> str:
    return _MANAGED_META_RE.sub("\n", source).rstrip() + "\n"


def render_strategy_file(code: str, meta: dict[str, Any]) -> str:
    validate_strategy_code(code)
    clean_code = strip_managed_meta(code)
    return (
        f"{clean_code}\n"
        f"{_MANAGED_META_START}\n"
        "# This block is generated by the Strategy Management API.\n"
        "# It intentionally overrides user-supplied STRATEGY_META safety fields.\n"
        f"STRATEGY_META = {meta!r}\n"
        f"{_MANAGED_META_END}\n"
    )


def managed_strategy_path(strategy_id: str) -> Path:
    validate_strategy_id(strategy_id)
    return GAWAIN_STRATEGY_ROOT / f"{strategy_id}.py"


def reload_strategies() -> dict[str, dict[str, Any]]:
    strategy_loader.discover()
    return strategy_loader.list_metadata()


def get_strategy_definition(strategy_id: str) -> StrategyDefinition:
    validate_strategy_id(strategy_id)
    return strategy_loader.get(strategy_id)


def create_strategy(payload: dict[str, Any]) -> dict[str, Any]:
    meta = forced_strategy_meta(payload)
    path = managed_strategy_path(meta["strategy_id"])
    if path.exists():
        raise FileExistsError(f"Strategy already exists: {meta['strategy_id']}")
    GAWAIN_STRATEGY_ROOT.mkdir(parents=True, exist_ok=True)
    path.write_text(render_strategy_file(str(payload["code"]), meta), encoding="utf-8")
    try:
        reload_strategies()
        return dict(get_strategy_definition(meta["strategy_id"]).meta)
    except Exception:
        path.unlink(missing_ok=True)
        reload_strategies()
        raise


def update_strategy(strategy_id: str, patch: dict[str, Any]) -> dict[str, Any]:
    definition = get_strategy_definition(strategy_id)
    path = definition.source_path
    if not _is_managed_gawain_path(path):
        raise PermissionError("Only strategies under strategies/gawain can be updated")

    original_source = path.read_text(encoding="utf-8")
    current_meta = dict(definition.meta)
    next_payload = {field: current_meta.get(field) for field in MANAGED_STRATEGY_FIELDS}
    next_payload["strategy_id"] = strategy_id
    for field in MANAGED_STRATEGY_FIELDS - {"strategy_id"}:
        if field in patch:
            next_payload[field] = patch[field]
    next_meta = forced_strategy_meta(next_payload)
    source = str(patch["code"]) if "code" in patch else original_source
    path.write_text(render_strategy_file(source, next_meta), encoding="utf-8")
    try:
        reload_strategies()
        return dict(get_strategy_definition(strategy_id).meta)
    except Exception:
        path.write_text(original_source, encoding="utf-8")
        reload_strategies()
        raise


def delete_strategy(strategy_id: str) -> dict[str, Any]:
    definition = get_strategy_definition(strategy_id)
    path = definition.source_path
    if not _is_managed_gawain_path(path):
        raise PermissionError("Builtin strategies cannot be deleted")
    path.unlink()
    return {"deleted": strategy_id, "strategies": reload_strategies()}


def validate_executable_strategy(strategy_id: str, parameters: dict[str, Any] | None = None) -> dict[str, Any]:
    try:
        reload_strategies()
        definition = get_strategy_definition(strategy_id)
        strategy = build_strategy(strategy_id, parameters or {})
        return {
            "valid": True,
            "strategy_id": strategy_id,
            "metadata": dict(definition.meta),
            "resolved_parameters": dict(strategy.params) if hasattr(strategy, "params") else {},
            "errors": [],
        }
    except Exception as exc:
        return {"valid": False, "strategy_id": strategy_id, "errors": [str(exc)]}


def _is_managed_gawain_path(path: Path) -> bool:
    try:
        return path.resolve().is_relative_to(GAWAIN_STRATEGY_ROOT.resolve())
    except AttributeError:
        root = GAWAIN_STRATEGY_ROOT.resolve()
        resolved = path.resolve()
        return root == resolved or root in resolved.parents
