import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api, type ExperimentResult, type ResearchAgentRecommendation, type ResearchAnalyticsResponse, type ResearchFeatureResponse } from '../services/api';

const datasets = [
  { dataset: 'candles_1m', symbol: 'BTCUSDT', interval: '1m', rows: 145230, oldest: '2024-01-01', latest: '2026-05-08T00:00:00Z', freshness: '14s', quality: 'good' },
];
const dist = [{ b: '-2σ', v: 4 }, { b: '-1σ', v: 12 }, { b: '0σ', v: 22 }, { b: '+1σ', v: 10 }, { b: '+2σ', v: 3 }];
const regime = [{ t: '09', v: 0.3 }, { t: '10', v: 0.5 }, { t: '11', v: 0.45 }, { t: '12', v: 0.62 }, { t: '13', v: 0.58 }];
const equity = [{ t: '09', v: 10000 }, { t: '10', v: 10080 }, { t: '11', v: 10120 }, { t: '12', v: 10090 }, { t: '13', v: 10160 }];

export function ResearchPage() {
  const [snapshot, setSnapshot] = useState<ResearchFeatureResponse | null>(null);
  const [symbol, setSymbol] = useState("BTCUSDT");
  const [activeSymbols, setActiveSymbols] = useState<string[]>(["BTCUSDT"]);
  const [experiments, setExperiments] = useState<ExperimentResult[]>([]);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [analytics, setAnalytics] = useState<ResearchAnalyticsResponse | null>(null);
  const [agentRecommendation, setAgentRecommendation] = useState<ResearchAgentRecommendation | null>(null);

  useEffect(() => {
    api.activeSymbols().then((res)=> setActiveSymbols(res.symbols.length ? res.symbols : ["BTCUSDT"])) .catch(()=>setActiveSymbols(["BTCUSDT"]));
  }, [symbol]);

  useEffect(() => {
    api.researchFeatures(symbol).then((res) => {
      setSnapshot(res);
      setLoadError(null);
    }).catch(() => {
      setSnapshot(null);
      setLoadError('Research feature telemetry unavailable');
    });
    api.latestExperiments(symbol).then((res) => setExperiments(res.experiments)).catch(() => setExperiments([]));
    api.researchAnalytics(symbol).then((res) => setAnalytics(res)).catch(() => setAnalytics(null));
    api.researchAgentRecommendations(symbol, '1m').then((res) => setAgentRecommendation(res)).catch(() => setAgentRecommendation(null));
  }, [symbol]);

  const featureRows = useMemo(() => {
    if (!snapshot) return [];
    return Object.entries(snapshot.features).map(([feature, latest]) => ({ feature, latest }));
  }, [snapshot]);

  return (<div className="space-y-3">
    <div><h1 className="text-xl font-semibold tracking-tight">Research Workspace</h1><p className="text-xs text-text-secondary">Read-only quantitative research and experiment monitoring.</p></div>
    <div className="flex items-center gap-2 text-xs"><span>Symbol</span><select value={symbol} onChange={(e)=>setSymbol(e.target.value)} className="rounded-md bg-surface-900 p-1 ring-1 ring-surface-700/60">{activeSymbols.map((s)=><option key={s} value={s}>{s}</option>)}</select></div><section className="grid grid-cols-2 gap-2 text-[11px] sm:grid-cols-6">
      <div className="rounded-md bg-surface-900 p-2 ring-1 ring-surface-700/60">Datasets available<div className="text-text-secondary">{datasets.length}</div></div>
      <div className="rounded-md bg-surface-900 p-2 ring-1 ring-surface-700/60">Real features tracked<div className="text-text-secondary">{featureRows.length}</div></div>
      <div className="rounded-md bg-surface-900 p-2 ring-1 ring-surface-700/60">Persisted experiments<div className="text-text-secondary">{experiments.length}</div></div>
      <div className="rounded-md bg-surface-900 p-2 ring-1 ring-surface-700/60">Feature status<div className="text-text-secondary">{snapshot?.quality.status ?? 'unavailable'}</div></div>
      <div className="rounded-md bg-surface-900 p-2 ring-1 ring-surface-700/60">Gaps detected<div className="text-text-secondary">{snapshot?.quality.gaps_detected ?? '-'}</div></div>
      <div className="rounded-md bg-surface-900 p-2 ring-1 ring-surface-700/60">Latest research run<div className="text-text-secondary">{experiments[0]?.experiment_id.slice(0, 10) ?? 'none'}</div></div>
    </section>
    <section className="rounded-lg bg-surface-900 p-3 ring-1 ring-surface-700/70 overflow-x-auto"><h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-text-muted">Feature Monitor (Real API Data)</h2>{loadError ? <div className="text-xs text-text-secondary">{loadError}. Showing empty state while experiment sections remain placeholders.</div> : <table className="w-full text-left text-[11px]"><thead className="text-text-muted"><tr><th>feature</th><th>latest value</th></tr></thead><tbody>{featureRows.map((f)=><tr key={f.feature} className="border-t border-surface-700/50"><td className="py-1.5 font-semibold">{f.feature}</td><td>{String(f.latest)}</td></tr>)}</tbody></table>}</section>
    <section className="rounded-lg bg-surface-900 p-3 ring-1 ring-surface-700/70 overflow-x-auto"><h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-text-muted">Experiment Runs (Persisted Research Memory)</h2>{experiments.length === 0 ? <div className="text-xs text-text-secondary">No persisted experiments yet. Run deterministic research with persistence enabled to build memory.</div> : <table className="w-full text-left text-[11px]"><thead className="text-text-muted"><tr><th>experiment id</th><th>strategy</th><th>dataset rows</th><th>Sharpe</th><th>max drawdown</th><th>win rate</th><th>status</th><th>type</th><th>created at</th></tr></thead><tbody>{experiments.map((r)=><tr key={r.experiment_id} className="border-t border-surface-700/50"><td className="py-1.5 font-semibold">{r.experiment_id.slice(0, 12)}</td><td>{r.strategy_name}</td><td>{r.dataset_row_count}</td><td>{r.sharpe}</td><td>{r.max_drawdown_pct}%</td><td>{r.win_rate_pct}%</td><td>{r.status}</td><td>{r.is_simulated ? "simulated deterministic" : "non-simulated"}</td><td>{r.created_at}</td></tr>)}</tbody></table>}<div className="mt-2 text-[10px] text-text-secondary">Research memory stores read-only analytical experiment outputs only (no trading or order execution).</div></section>

    <section className="rounded-lg bg-surface-900 p-3 ring-1 ring-surface-700/70 overflow-x-auto"><h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-text-muted">Research Analytics</h2>{!analytics || analytics.summary.total_experiments === 0 ? <div className="text-xs text-text-secondary">No analytics available yet. Persist deterministic research experiments to populate leaderboard and regime breakdown.</div> : <><div className="grid grid-cols-2 gap-2 text-[11px] sm:grid-cols-5"><div className="rounded-md bg-surface-850 p-2">Top strategy<div className="text-text-secondary">{analytics.summary.best_strategy_by_sharpe?.strategy_name ?? 'n/a'}</div></div><div className="rounded-md bg-surface-850 p-2">Best Sharpe<div className="text-text-secondary">{analytics.summary.best_strategy_by_sharpe?.sharpe ?? '-'}</div></div><div className="rounded-md bg-surface-850 p-2">Best Return<div className="text-text-secondary">{analytics.summary.best_strategy_by_return?.total_return_pct ?? '-'}%</div></div><div className="rounded-md bg-surface-850 p-2">Worst Drawdown<div className="text-text-secondary">{analytics.summary.worst_strategy_by_drawdown?.max_drawdown_pct ?? '-'}%</div></div><div className="rounded-md bg-surface-850 p-2">Total Experiments<div className="text-text-secondary">{analytics.summary.total_experiments}</div></div></div><div className="mt-3"><h3 className="text-xs text-text-muted mb-1">Strategy Leaderboard</h3><table className="w-full text-left text-[11px]"><thead className="text-text-muted"><tr><th>strategy</th><th>avg sharpe</th><th>avg return</th><th>win rate</th><th>trades</th></tr></thead><tbody>{analytics.strategy_leaderboard.map((r)=><tr key={r.strategy_name} className="border-t border-surface-700/50"><td className="py-1.5 font-semibold">{r.strategy_name}</td><td>{r.average_sharpe}</td><td>{r.average_return_pct}%</td><td>{r.win_rate_pct}%</td><td>{r.trade_count}</td></tr>)}</tbody></table></div><div className="mt-3"><h3 className="text-xs text-text-muted mb-1">Regime Breakdown</h3><table className="w-full text-left text-[11px]"><thead className="text-text-muted"><tr><th>regime</th><th>experiments</th><th>avg sharpe</th><th>avg return</th><th>avg drawdown</th></tr></thead><tbody>{analytics.regime_breakdown.map((r)=><tr key={r.regime} className="border-t border-surface-700/50"><td className="py-1.5 font-semibold">{r.regime}</td><td>{r.experiments}</td><td>{r.average_sharpe}</td><td>{r.average_return_pct}%</td><td>{r.average_drawdown_pct}%</td></tr>)}</tbody></table></div></>}</section>

    <section className="rounded-lg bg-surface-900 p-3 ring-1 ring-surface-700/70 overflow-x-auto"><h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-text-muted">Research Agent v0 (Deterministic / Rule-Based)</h2>{!agentRecommendation ? <div className="text-xs text-text-secondary">Agent recommendation unavailable.</div> : <><div className="text-[11px] text-text-secondary">This agent is recommendation-only and does not perform autonomous trading, order execution, or strategy registry modification.</div><div className="mt-2 grid grid-cols-1 gap-2 sm:grid-cols-3 text-[11px]"><div className="rounded-md bg-surface-850 p-2">Overfit risk<div className="text-text-secondary">{agentRecommendation.overfit_risk.label}</div></div><div className="rounded-md bg-surface-850 p-2">Strategy assessments<div className="text-text-secondary">{agentRecommendation.strategy_assessments.length}</div></div><div className="rounded-md bg-surface-850 p-2">Recommendations<div className="text-text-secondary">{agentRecommendation.recommended_experiments.length}</div></div></div><div className="mt-3"><h3 className="text-xs text-text-muted mb-1">Research Summary</h3><ul className="list-disc pl-4 text-[11px]">{agentRecommendation.research_summary.notes.map((n) => <li key={n}>{n}</li>)}</ul></div><div className="mt-3"><h3 className="text-xs text-text-muted mb-1">Recommended Experiments</h3><table className="w-full text-left text-[11px]"><thead className="text-text-muted"><tr><th>strategy</th><th>reason</th><th>priority</th><th>safety note</th></tr></thead><tbody>{agentRecommendation.recommended_experiments.map((r, idx)=><tr key={`${r.strategy_name}-${idx}`} className="border-t border-surface-700/50"><td className="py-1.5 font-semibold">{r.strategy_name}</td><td>{r.reason}</td><td>{r.priority}</td><td>{r.safety_note}</td></tr>)}</tbody></table></div><div className="mt-3"><h3 className="text-xs text-text-muted mb-1">Rejected Strategies</h3>{agentRecommendation.rejected_strategies.length === 0 ? <div className="text-[11px] text-text-secondary">None</div> : <ul className="list-disc pl-4 text-[11px]">{agentRecommendation.rejected_strategies.map((r) => <li key={r.strategy_name}>{r.strategy_name}: {r.reason}</li>)}</ul>}</div><div className="mt-3"><h3 className="text-xs text-text-muted mb-1">Next Actions</h3><ul className="list-disc pl-4 text-[11px]">{agentRecommendation.next_actions.map((n) => <li key={n}>{n}</li>)}</ul></div></>}</section>
    <section className="grid grid-cols-1 gap-2 md:grid-cols-2"><div className="rounded-lg bg-surface-900 p-3 ring-1 ring-surface-700/70"><h3 className="mb-2 text-xs text-text-muted">Return distribution</h3><div className="h-24"><ResponsiveContainer><BarChart data={dist}><CartesianGrid stroke="#252d3a" strokeOpacity={0.2} vertical={false}/><XAxis dataKey="b" hide/><YAxis hide/><Tooltip contentStyle={{background:'#12161d',border:'1px solid #252d3a'}}/><Bar dataKey="v" fill="#6f8fdc"/></BarChart></ResponsiveContainer></div></div><div className="rounded-lg bg-surface-900 p-3 ring-1 ring-surface-700/70"><h3 className="mb-2 text-xs text-text-muted">Volatility regime trend</h3><div className="h-24"><ResponsiveContainer><LineChart data={regime}><CartesianGrid stroke="#252d3a" strokeOpacity={0.2} vertical={false}/><XAxis dataKey="t" hide/><YAxis hide/><Tooltip contentStyle={{background:'#12161d',border:'1px solid #252d3a'}}/><Line type="monotone" dataKey="v" stroke="#6f8fdc" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div></div><div className="rounded-lg bg-surface-900 p-3 ring-1 ring-surface-700/70"><h3 className="mb-2 text-xs text-text-muted">Feature correlation placeholder</h3><div className="flex h-24 items-center justify-center rounded bg-surface-850 text-xs text-text-secondary">Correlation heatmap integration pending.</div></div><div className="rounded-lg bg-surface-900 p-3 ring-1 ring-surface-700/70"><h3 className="mb-2 text-xs text-text-muted">Backtest equity curve placeholder</h3><div className="h-24"><ResponsiveContainer><LineChart data={equity}><CartesianGrid stroke="#252d3a" strokeOpacity={0.2} vertical={false}/><XAxis dataKey="t" hide/><YAxis hide/><Tooltip contentStyle={{background:'#12161d',border:'1px solid #252d3a'}}/><Line type="monotone" dataKey="v" stroke="#ac9060" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div></div></section>
  </div>);
}
